version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: "theraw/dopemail:rabbitmq-server"
    shm_size: '512MB'
    privileged: true
    restart: unless-stopped
    networks:
      postal_net:
        ipv4_address: 172.33.0.7
    ulimits:
     nproc: 655355
    cap_add:
      - ALL
    command: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
  mysql:
    container_name: mysql
    image: "theraw/dopemail:mysql"
    shm_size: '512MB'
    privileged: true
    restart: unless-stopped
    networks:
      postal_net:
        ipv4_address: 172.33.0.6
    ulimits:
     nproc: 655355
    cap_add:
      - ALL
    command: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf"]
  postal:
    hostname: mail
    domainname: rawmail.nl
    container_name: postal
    image: "theraw/dopemail:smtp"
    shm_size: '512MB'
    privileged: true
    restart: unless-stopped
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:25:25'
      - '0.0.0.0:2525:2525'
    networks:
      postal_net:
        ipv4_address: 172.33.0.5
    ulimits:
     nproc: 655355
    cap_add:
      - ALL
    command: ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/supervisord.conf"]
networks:
  postal_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.33.0.0/16
